# Generated by Django 3.1 on 2021-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(choices=[('Color', 'Color'), ('Size', 'Size')], max_length=100),
        ),
    ]
